name: ColorbarSalonBham
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25743
title: 'Colorbar Salon Birmingham '
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f7f7'
    - '#5d9b82'
    - '#4e7093'
    - '#d99595'
    - '#3d3644'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
